// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFXNDIt-O9Se5g9GEc6p6QNFB655jI7rk',
    appId: '1:359478841267:web:672c11d95b60f79e6405c6',
    messagingSenderId: '359478841267',
    projectId: 'flutter-bloc-app-46df4',
    authDomain: 'flutter-bloc-app-46df4.firebaseapp.com',
    storageBucket: 'flutter-bloc-app-46df4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa1cAUDyBsxZIjBMsleuLfXx49-V6nhlE',
    appId: '1:359478841267:android:b574a25f1d30a8406405c6',
    messagingSenderId: '359478841267',
    projectId: 'flutter-bloc-app-46df4',
    storageBucket: 'flutter-bloc-app-46df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbmwZx9fJfXM4Hdd55zXpoWrupgKnPdX0',
    appId: '1:359478841267:ios:787793f56eb2682f6405c6',
    messagingSenderId: '359478841267',
    projectId: 'flutter-bloc-app-46df4',
    storageBucket: 'flutter-bloc-app-46df4.firebasestorage.app',
    iosBundleId: 'com.example.imageBlocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbmwZx9fJfXM4Hdd55zXpoWrupgKnPdX0',
    appId: '1:359478841267:ios:787793f56eb2682f6405c6',
    messagingSenderId: '359478841267',
    projectId: 'flutter-bloc-app-46df4',
    storageBucket: 'flutter-bloc-app-46df4.firebasestorage.app',
    iosBundleId: 'com.example.imageBlocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFXNDIt-O9Se5g9GEc6p6QNFB655jI7rk',
    appId: '1:359478841267:web:919cd7da170dad4c6405c6',
    messagingSenderId: '359478841267',
    projectId: 'flutter-bloc-app-46df4',
    authDomain: 'flutter-bloc-app-46df4.firebaseapp.com',
    storageBucket: 'flutter-bloc-app-46df4.firebasestorage.app',
  );
}
